name: Publish gh-pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  node-version: 16.x

jobs:
  build:
    name: Build-deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout current repo
      uses: actions/checkout@v3
    
    - name: Use Node.js ${{ env.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.node-version }}
        cache: 'npm'
    
    - name: Cache node_modules
      id: node_modules
      uses: actions/cache@v3
      with:
        path: ./node_modules
        key: node_modules-${{ hashFiles('./package*.json') }}

    - name: Run npm install
      if: steps.node_modules.outputs.cache-hit != 'true'
      run: npm install

    - name: Build project
      run: npm run build -- --prod --base-href "https://dilorfin.github.io/till-tomorrow/"
    
    # workaround till (https://github.com/angular/angular-cli/issues/16997)
    - name: Localization copying
      run: cp dist/till-tomorrow/uk/* dist/till-tomorrow && rm -rf dist/till-tomorrow/uk
      shell: bash

    - name: Deploy to gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npx angular-cli-ghpages --dir=dist/till-tomorrow --name=${{ secrets.USERNAME }} --email=${{ secrets.EMAIL }} --no-silent
